### ISSUE TITLE
database

### ISSUE THREAD

**Issue by karimwarp** [DevExpress-Examples/how-to-display-a-custom-tooltip-when-hovering-with-the-mouse-over-an-appointment-e3224#1]
can i get a copy of the cars database

**Comment by zabelin-vladimir** [comment]
I've attached it to this reply. 
[CarXtraScheduling.zip](https://github.com/DevExpress-Examples/how-to-display-a-custom-tooltip-when-hovering-with-the-mouse-over-an-appointment-e3224/files/3054424/CarXtraScheduling.zip)
 
If you have any other questions regarding this or our other examples, please submit a corresponding ticket in our Support Center (this is our official support channel) rather than GitHub:
https://www.devexpress.com/Support/Center/Question/Create
 
We will process your request in the most efficient way.
 
If you do not have a DevExpress account, please register on our website to get access to the Support Center:
https://www.devexpress.com/MyAccount/Register/
